// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PotholeDetectorWebApp.Models;
using System;

namespace PotholeDetectorWebApp.Migrations
{
    [DbContext(typeof(WebAppContext))]
    partial class WebAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("PotholeDetectorWebApp.Models.Pothole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NumberOfPotholes");

                    b.Property<DateTime>("createdAt");

                    b.Property<DateTime>("date");

                    b.Property<string>("lat");

                    b.Property<string>("lon");

                    b.Property<string>("time");

                    b.Property<DateTime>("updatedAt");

                    b.HasKey("id");

                    b.ToTable("Potholes");
                });
#pragma warning restore 612, 618
        }
    }
}
